"""add_group_fields_to_questions

Revision ID: d0ef6ed3cbe0
Revises: 20260415_0007
Create Date: 2026-04-15 21:41:05.434805

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = 'd0ef6ed3cbe0'
down_revision = '20260415_0007'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('group_session_id', sa.Integer(), nullable=True))
    op.add_column('questions', sa.Column('round_index', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_questions_group_session_id'), 'questions', ['group_session_id'], unique=False)
    op.create_foreign_key(None, 'questions', 'group_interview_sessions', ['group_session_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.drop_index(op.f('ix_questions_group_session_id'), table_name='questions')
    op.drop_column('questions', 'round_index')
    op.drop_column('questions', 'group_session_id')
    # ### end Alembic commands ###
